// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5GbIAgp76oKxT7ZPXK3RbLDUeeKdbxTg',
    appId: '1:961259810153:web:3460f79e82ba51ebd521f8',
    messagingSenderId: '961259810153',
    projectId: 'flutter-roadmap-app',
    authDomain: 'flutter-roadmap-app.firebaseapp.com',
    storageBucket: 'flutter-roadmap-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd557x41ZGGnfyudS6xxTpILJk_Uq50po',
    appId: '1:961259810153:android:62dd23dd8316f5a5d521f8',
    messagingSenderId: '961259810153',
    projectId: 'flutter-roadmap-app',
    storageBucket: 'flutter-roadmap-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEWQztgYp7Kgs254qSUdcZ5tyefBkOU4c',
    appId: '1:961259810153:ios:5ed53e3bfe5f78c9d521f8',
    messagingSenderId: '961259810153',
    projectId: 'flutter-roadmap-app',
    storageBucket: 'flutter-roadmap-app.appspot.com',
    iosClientId: '961259810153-dik69d2sa6ljih22aro5pg45nufslgll.apps.googleusercontent.com',
    iosBundleId: 'com.hrvoje.flutter-roadmap',
  );
}
