// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ9MQgBZWtPSJ0Q4epkeVt15gFnwl99Js',
    appId: '1:691277725181:web:71a42b162146cbd80e2d94',
    messagingSenderId: '691277725181',
    projectId: 'rollplus-d7cf3',
    authDomain: 'rollplus-d7cf3.firebaseapp.com',
    storageBucket: 'rollplus-d7cf3.appspot.com',
    measurementId: 'G-EQWN0HVHFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmf__wPnPU75OrUcKi8z4w1NWUh1STpX0',
    appId: '1:691277725181:android:1f4fffac269defd70e2d94',
    messagingSenderId: '691277725181',
    projectId: 'rollplus-d7cf3',
    storageBucket: 'rollplus-d7cf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJRYsGug-D4-EWzT-9v0FE5J8yCvseB_Y',
    appId: '1:691277725181:ios:a9f42b0f3ec84dbe0e2d94',
    messagingSenderId: '691277725181',
    projectId: 'rollplus-d7cf3',
    storageBucket: 'rollplus-d7cf3.appspot.com',
    iosClientId: '691277725181-css25nkma4r8ctr0tangtkar6orutu8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginTemplateFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJRYsGug-D4-EWzT-9v0FE5J8yCvseB_Y',
    appId: '1:691277725181:ios:a9f42b0f3ec84dbe0e2d94',
    messagingSenderId: '691277725181',
    projectId: 'rollplus-d7cf3',
    storageBucket: 'rollplus-d7cf3.appspot.com',
    iosClientId: '691277725181-css25nkma4r8ctr0tangtkar6orutu8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginTemplateFirebase',
  );
}
